// Generated by script/generate-api-contract.py; edit internal/http/contract/spec.json.

export type InstanceKey = {
  "Hostname": string;
  "Port": number;
};

export type NullableNumber = {
  "Int64": number;
  "Valid": boolean;
};

export type Coordinates = {
  "LogFile": string;
  "LogPos": number;
  "Type"?: number;
};

export type Instance = {
  "Key": InstanceKey;
  "MasterKey": InstanceKey;
  "ClusterName": string;
  "InstanceAlias"?: string;
  "Version": string;
  "ReadOnly": boolean;
  "IsCoMaster": boolean;
  "IsLastCheckValid": boolean;
  "IsRecentlyChecked": boolean;
  "IsUpToDate": boolean;
  "ReplicationDepth": number;
  "ReplicationSQLThreadRuning": boolean;
  "ReplicationIOThreadRuning": boolean;
  "ReplicationLagSeconds": NullableNumber;
  "SecondsBehindMaster": NullableNumber;
  "SecondsSinceLastSeen": NullableNumber;
  "SQLDelay": number;
  "Uptime": number;
  "DataCenter": string;
  "PhysicalEnvironment": string;
  "LogBinEnabled": boolean;
  "LogReplicationUpdatesEnabled": boolean;
  "Binlog_format": string;
  "UsingOracleGTID": boolean;
  "UsingMariaDBGTID": boolean;
  "UsingPseudoGTID": boolean;
  "SupportsOracleGTID": boolean;
  "GtidErrant": string;
  "ExecutedGtidSet": string;
  "SelfBinlogCoordinates": Coordinates;
  "ExecBinlogCoordinates": Coordinates;
  "ReadBinlogCoordinates": Coordinates;
  "RelaylogCoordinates": Coordinates;
  "LastSQLError": string;
  "LastIOError": string;
  "Replicas"?: (InstanceKey)[] | null;
  "IsDowntimed": boolean;
  "DowntimeOwner": string;
  "DowntimeReason": string;
  "DowntimeEndTimestamp": string;
  "PromotionRule": string;
  "SemiSyncMasterEnabled": boolean;
  "SemiSyncReplicaEnabled": boolean;
  "Problems"?: (string)[] | null;
};

export type Cluster = {
  "ClusterName": string;
  "ClusterAlias": string;
  "ClusterDomain": string;
  "CountInstances": number;
  "HasAutomatedMasterRecovery": boolean;
  "HasAutomatedIntermediateMasterRecovery": boolean;
};

export type Analysis = {
  "Analysis": string;
  "AnalyzedInstanceKey": InstanceKey;
  "ClusterDetails": Cluster;
  "StructureAnalysis"?: (string)[] | null;
  "Description"?: string;
  "IsDowntimed": boolean;
  "CountReplicas": number;
  "CountValidReplicas": number;
  "CountValidReplicatingReplicas": number;
  "Replicas"?: (InstanceKey)[] | null;
};

export type Maintenance = {
  "MaintenanceId": number;
  "Key": InstanceKey;
  "Owner": string;
  "Reason": string;
  "BeginTimestamp": string;
  "SecondsElapsed": number;
  "IsActive": boolean;
};

export type Recovery = {
  "Id": number;
  "UID": string;
  "AnalysisEntry": Analysis;
  "IsActive": boolean;
  "IsSuccessful": boolean;
  "RecoveryStartTimestamp": string;
  "RecoveryEndTimestamp": string;
  "ProcessingNodeHostname": string;
  "Acknowledged": boolean;
  "AcknowledgedBy": string;
  "AcknowledgedAt": string;
  "AcknowledgedComment": string;
  "SuccessorKey": InstanceKey | null;
  "LostReplicas": (InstanceKey)[] | null;
  "ParticipatingInstanceKeys": (InstanceKey)[] | null;
  "AllErrors": (string)[] | null;
  "LastDetectionId": number;
  "RelatedRecoveryId"?: number;
};

export type RecoveryStep = {
  "Id": number;
  "RecoveryUID": string;
  "AuditAt": string;
  "Message": string;
};

export type Audit = {
  "AuditId": number;
  "AuditTimestamp": string;
  "AuditType": string;
  "AuditInstanceKey": InstanceKey;
  "Message": string;
};

export type BlockedRecovery = {
  "FailedInstanceKey": InstanceKey;
  "ClusterName": string;
  "Analysis": string;
  "BlockingRecoveryId": number;
  "LastBlockedTimestamp": string;
};

export type Seed = {
  "SeedId": number;
  "TargetHostname": string;
  "SourceHostname": string;
  "IsComplete": boolean;
  "IsSuccessful": boolean;
  "StartTimestamp": string;
  "EndTimestamp": string;
};

export type SeedState = {
  "SeedStateId": number;
  "StateTimestamp": string;
  "Action": string;
  "ErrorMessage": string;
};

export type Agent = {
  "Hostname": string;
  "Port": number;
  "MySQLPort": number;
  "LastSubmitted": string;
  "MySQLRunning": boolean;
  "MySQLDiskUsage": number;
  "MySQLErrorLogTail": (string)[] | null;
  "AvailableSnapshots": (string)[] | null;
  "AvailableLocalSnapshots": (string)[] | null;
  "LogicalVolumes": ({
  "Name": string;
  "GroupName": string;
  "Path": string;
  "IsSnapshot": boolean;
  "SnapshotPercent": number;
})[] | null;
  "MountPoint": {
  "IsMounted": boolean;
  "Path": string;
  "Device": string;
  "DiskUsage": number;
};
};

export type WebConfig = {
  "urlPrefix": string;
  "userId": string;
  "authorizedForAction": boolean;
  "authorizedForConfiguration": boolean;
  "agentsEnabled": boolean;
  "pseudoGTIDEnabled": boolean;
  "removeTextFromHostnameDisplay": string;
  "webMessage": string;
  "auditPageSize": number;
  "auditEnabled": boolean;
};

export type RecoveryPolicy = {
  "autoMasterRecovery": boolean;
  "autoIntermediateMasterRecovery": boolean;
  "recoveryIgnoreHostnameFilters": (string)[] | null;
  "promotionIgnoreHostnameFilters": (string)[] | null;
  "problemIgnoreHostnameFilters": (string)[] | null;
  "failureDetectionPeriodBlockMinutes": number;
  "recoveryPeriodBlockSeconds": number;
  "reasonableReplicationLagSeconds": number;
  "reasonableMaintenanceReplicationLagSeconds": number;
  "verifyReplicationFilters": boolean;
  "failMasterPromotionOnLagMinutes": number;
  "sqlThreadPromotionPolicy": "allow" | "wait" | "reject";
  "recoverNonWriteableMaster": boolean;
  "coMasterRecoveryMustPromoteOtherCoMaster": boolean;
  "detachLostReplicasAfterMasterFailover": boolean;
  "applyMySQLPromotionAfterMasterFailover": boolean;
  "preventCrossDataCenterMasterFailover": boolean;
  "preventCrossRegionMasterFailover": boolean;
  "masterFailoverDetachReplicaMasterHost": boolean;
  "postponeReplicaRecoveryOnLagMinutes": number;
  "enforceExactSemiSyncReplicas": boolean;
  "recoverLockedSemiSyncMaster": boolean;
  "reasonableLockedSemiSyncMasterSeconds": number;
};

export type RecoveryPolicyDocument = {
  "scopeType": "global" | "cluster";
  "scopeKey": string;
  "revision": number;
  "overrides": Partial<RecoveryPolicy>;
  "inherited": RecoveryPolicy;
  "effective": RecoveryPolicy;
  "updatedBy"?: string;
  "changeReason"?: string;
  "updatedAt"?: string;
};

export type HookProfile = {
  "id": string;
  "name": string;
  "commands": (string)[] | null;
  "timeoutSeconds": number;
  "failurePolicy": "abort" | "continue";
  "outputLimitBytes": number;
  "enabled": boolean;
  "revision": number;
  "updatedBy"?: string;
  "changeReason"?: string;
};

export type HookAssignment = {
  "scopeType": "global" | "cluster";
  "scopeKey": string;
  "phase": string;
  "mode": "inherit" | "replace" | "disable";
  "profileIds": (string)[] | null;
  "revision": number;
  "changeReason"?: string;
};

export type Envelope<T = unknown> = {
  "Code": "OK" | "ERROR";
  "Message": string;
  "Details": T;
  "ErrorClass"?: "invalid_argument" | "raft_unavailable" | "not_bootstrapped" | "not_leader" | "conflict" | "not_found" | "failed" | "indeterminate";
};
