FROM node:22.22.2-bookworm-slim AS web-build
WORKDIR /web
RUN npm install --global pnpm@10.33.2
COPY web/package.json web/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY web/ ./
RUN pnpm build

FROM golang:1.27.0-bookworm
LABEL maintainer="openark@github.com"

RUN apt-get update -q -y
RUN apt-get install -y sudo lsb-release rsync libaio1 numactl sqlite3 git jq less vim python-is-python3 2to3 bsdmainutils make

COPY docker/resources/systemctl.py /usr/bin/systemctl

RUN mkdir /orchestrator
WORKDIR /orchestrator

COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY --from=web-build /web/dist/ /orchestrator/web/assets/
ENV WEB_PREBUILT=1
RUN make build

CMD (cd /orchestrator && docker/docker-entry-raft && /bin/bash)
