FROM node:22.22.2-bookworm-slim AS web-build
WORKDIR /web
RUN npm install --global pnpm@10.33.2
COPY web/package.json web/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY web/ ./
RUN pnpm build

FROM golang:1.27.0-bookworm
LABEL maintainer="openark@github.com"

RUN apt-get update
RUN apt-get install -y lsb-release rsync libaio1 numactl sqlite3 libncurses5 libtinfo5 make
RUN rm -rf /var/lib/apt/lists/*

ENV WORKPATH=/orchestrator
WORKDIR $WORKPATH

COPY go.mod go.sum ./
RUN go mod download

# Setup dbdeployer
RUN mkdir /dbdeployer
RUN (cd /dbdeployer && wget https://github.com/datacharmer/dbdeployer/releases/download/v1.64.0/dbdeployer-1.64.0.linux.tar.gz)
RUN (cd /dbdeployer && tar -xf dbdeployer-1.64.0.linux.tar.gz)
RUN (cd /dbdeployer && ln -s dbdeployer-1.64.0.linux dbdeployer)
RUN (cd /dbdeployer && ./dbdeployer defaults update reserved-ports '0')

# For dev purposes only, just to avoid downloading over and over via download-mysql script
# RUN (mkdir /mysql-tarballs-downloaded)
# COPY docker/Percona-Server-8.0.26-16-Linux.x86_64.glibc2.12-minimal.tar.gz /mysql-tarballs-downloaded/ 

COPY . .
COPY --from=web-build /web/dist/ /orchestrator/web/assets/
ENV WEB_PREBUILT=1
RUN (cd /dbdeployer && ./dbdeployer defaults update reserved-ports '0')

ENV TARBAL_URL_DEFAULT https://raw.githubusercontent.com/percona/orchestrator-ci-env/master/mysql-tarballs/mysql-5.7.26.tar.xz
CMD ["make", "test-container"]
