FROM golang:1.26.5-bookworm
LABEL maintainer="kamil.holubicki@percona.com"

RUN apt-get update \
    && apt-get install -y --no-install-recommends make \
    && rm -rf /var/lib/apt/lists/*

ENV WORKPATH=/orchestrator
WORKDIR $WORKPATH

COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["make", "cve"]
