#!/bin/bash

set -e

orch enable-semi-sync-master -i 127.0.0.1:10111
orch enable-semi-sync-replica -i 127.0.0.1:10112
orch enable-semi-sync-replica -i 127.0.0.1:10113
orch enable-semi-sync-replica -i 127.0.0.1:10114
sleep 10
