#!/bin/bash

# Compatibility entrypoint. New callers should invoke the matching Make target.

set -e

command="$1"

case "$command" in
  cve) exec make docker-cve ;;
  cve-no-it) exec make docker-cve DOCKER_TTY= ;;
  test) exec make docker-test ;;
  test-no-it) exec make docker-test DOCKER_TTY= ;;
  alpine) exec make run ;;
  hub) exec make hub-image ;;
  pkg) exec make package PACKAGES_PATH="${2:-/tmp/orchestrator-release}" ;;
  system) exec make system ;;
  system-no-it) exec make system DOCKER_TTY= ;;
  raft) exec make raft ;;
  *)
    >&2 echo "Usage: script/dock <cve|test|alpine|hub|pkg|system|raft> [arg]"
    exit 1
    ;;
esac
