#!/bin/bash

export ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$ROOTDIR"

if ! command -v go >/dev/null 2>&1; then
  echo "go binary not found in PATH"
  exit 1
fi

echo "$(go version) found: Go Binary: $(command -v go)"
