#!/usr/bin/env python3
"""Generate checked-in clients and reference from the canonical API contract."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'internal/http/contract/spec.json'


def typescript(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if 'x-partial' in schema:
        return 'Partial<' + schema['x-partial'] + '>'
    if 'x-typescript' in schema:
        return schema['x-typescript']
    if 'enum' in schema:
        return ' | '.join(json.dumps(v) for v in schema['enum'])
    if 'anyOf' in schema:
        return ' | '.join(typescript(v) for v in schema['anyOf'])
    kind = schema.get('type')
    if isinstance(kind, list):
        return ' | '.join(typescript(dict(schema, type=t)) for t in kind)
    if kind == 'array':
        return '(' + typescript(schema['items']) + ')[]'
    if kind == 'object':
        if 'properties' not in schema:
            return 'Record<string, ' + typescript(schema.get('additionalProperties', {})) + '>'
        required = schema.get('required', [])
        return '{\n' + ''.join('  ' + json.dumps(k) + ('' if k in required else '?') + ': ' + typescript(v) + ';\n' for k, v in schema['properties'].items()) + '}'
    return {'string': 'string', 'number': 'number', 'integer': 'number', 'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')


def outputs(spec):
    types = '// Generated by script/generate-api-contract.py; edit internal/http/contract/spec.json.\n\n'
    for name, schema in spec['$defs'].items():
        generic = '<T = unknown>' if schema.get('x-generic') else ''
        types += 'export type ' + name + generic + ' = ' + typescript(schema) + ';\n\n'
    endpoints = [{k: e[k] for k in ('method', 'path', 'readOnly')} for e in spec['endpoints']]
    reference = '# HTTP 接口契约\n\n此文件由 `make api-contract` 生成；源定义为 `internal/http/contract/spec.json`。\n\n'
    reference += '路径不含部署前缀。`readOnly` 表示操作语义，不能根据 GET 推断。响应列中的 `legacy` 表示历史接口返回格式不统一；空 schema 保留动态 Details，不宣称字段已验证。错误使用 Envelope，ErrorClass 为可选分类。\n\n'
    reference += '| 方法 | 路径 | 只读 | 响应 |\n| --- | --- | --- | --- |\n'
    for e in spec['endpoints']:
        response = e['response']
        reference += f"| {e['method']} | `{e['path']}` | {'是' if e['readOnly'] else '否'} | {response['kind']}: `{typescript(response['schema'])}` |\n"
    return {
        'tools/orch-cli/internal/cmd/catalog.json': json.dumps(spec['commands'], indent=2, ensure_ascii=False) + '\n',
        'web/src/api/types.ts': types.rstrip() + '\n',
        'web/src/api/endpoints.json': json.dumps(endpoints, indent=2) + '\n',
        'docs/architecture/api-contract.md': reference,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='report stale generated files without writing')
    args = parser.parse_args()
    spec = json.loads(SOURCE.read_text())
    routes = [(e['method'], e['path']) for e in spec['endpoints']]
    if len(set(routes)) != len(routes):
        raise SystemExit('duplicate endpoint in API contract')
    stale = []
    for relative, content in outputs(spec).items():
        target = ROOT / relative
        if not target.exists() or target.read_text() != content:
            stale.append(relative)
            if not args.check:
                target.write_text(content)
    if args.check and stale:
        raise SystemExit('Run make api-contract; stale files: ' + ', '.join(stale))
    print('API contract: ' + ('verified' if args.check else 'generated') + f' ({len(routes)} routes)')


if __name__ == '__main__':
    main()
