#!/bin/bash

set -u

check_for_cves() {
  local vulncheck_log=vulncheck.log
  local govulncheck_binary="${GOVULNCHECK:-govulncheck}"
  local scan_status
 
  echo "# Verifying if the code is affected by CVEs (vulncheck)"
  "$govulncheck_binary" -show verbose ./... | tee "$vulncheck_log"
  scan_status=${PIPESTATUS[0]}
  
  content=$(tr '\n' ' ' < "$vulncheck_log")
  
  affecting_cves_cnt=$(echo "$content" | sed -nE 's/.*Your code is affected by ([0-9]+).*/\1/p')
  waring_package_cves_cnt=$(echo "$content" | sed -nE 's/.*This scan also found ([0-9]+).*/\1/p')
  waring_import_cves_cnt=$(echo "$content" | sed -nE 's/.*and ([0-9]+) vulnerabilit(y|ies) in modules you require.*/\1/p')
  affecting_cves_cnt=${affecting_cves_cnt:-0}
  waring_package_cves_cnt=${waring_package_cves_cnt:-0}
  waring_import_cves_cnt=${waring_import_cves_cnt:-0}

  echo "affecting_cves_cnt:       $affecting_cves_cnt"
  echo "waring_package_cves_cnt:  $waring_package_cves_cnt"
  echo "waring_import_cves_cnt:   $waring_import_cves_cnt"

  if [[ $scan_status -ne 0 && $affecting_cves_cnt -eq 0 && $waring_package_cves_cnt -eq 0 && $waring_import_cves_cnt -eq 0 ]]; then
    result=FAILED
  elif [[ $affecting_cves_cnt -eq 0 && $waring_package_cves_cnt -eq 0 && $waring_import_cves_cnt -eq 0 ]]; then
    result=PASSED
  elif [[ $affecting_cves_cnt -eq 0 && ( $waring_package_cves_cnt -ne 0 || $waring_import_cves_cnt -ne 0) ]]; then
    result=WARNING
  else
    result=FAILED
  fi
  
  echo "CVE check result: $result"
  [[ "$result" != "FAILED" ]]
}


check_for_cves
