#!/bin/bash

echo "# topology:"
orch topology-tabulated --alias ci
echo "# replication-analysis:"
orch replication-analysis
if [ -f /etc/haproxy/haproxy.cfg ] ; then
  echo "# haproxy"
  cat /etc/haproxy/haproxy.cfg
fi
