#!/bin/bash

echo "# Reloading configuration"
orch api "reload-configuration" | jq -r '.Code'
orch ack-all-recoveries --reason "system-tests"
orch all-instances | while read i ; do
  orch end-downtime -i $i
  orch register-candidate -i $i --promotion-rule neutral
done
