package main

import "slices"

// commandDefinition 描述一个业务命令；目录读取不执行命令或初始化外部资源。
type commandDefinition struct {
	Command     string
	Section     string
	Description string
	Aliases     []string
}

var commandSynonyms = map[string]string{
	"stop-slave":                  "stop-replica",
	"start-slave":                 "start-replica",
	"restart-slave":               "restart-replica",
	"reset-slave":                 "reset-replica",
	"restart-slave-statements":    "restart-replica-statements",
	"relocate-slaves":             "relocate-replicas",
	"regroup-slaves":              "regroup-replicas",
	"move-up-slaves":              "move-up-replicas",
	"repoint-slaves":              "repoint-replicas",
	"enslave-siblings":            "take-siblings",
	"enslave-master":              "take-master",
	"get-candidate-slave":         "get-candidate-replica",
	"move-slaves-gtid":            "move-replicas-gtid",
	"regroup-slaves-gtid":         "regroup-replicas-gtid",
	"match-slaves":                "match-replicas",
	"match-up-slaves":             "match-up-replicas",
	"regroup-slaves-pgtid":        "regroup-replicas-pgtid",
	"which-cluster-osc-slaves":    "which-cluster-osc-replicas",
	"which-cluster-gh-ost-slaves": "which-cluster-gh-ost-replicas",
	"which-slaves":                "which-replicas",
	"detach-slave":                "detach-replica-master-host",
	"detach-replica":              "detach-replica-master-host",
	"detach-slave-master-host":    "detach-replica-master-host",
	"reattach-slave":              "reattach-replica-master-host",
	"reattach-replica":            "reattach-replica-master-host",
	"reattach-slave-master-host":  "reattach-replica-master-host",
}

var knownCommands = []commandDefinition{
	{Command: "relocate", Section: "Smart relocation", Description: `Relocate a replica beneath another instance`},
	{Command: "relocate-below", Section: "Smart relocation", Description: `Synonym to 'relocate', will be deprecated`},
	{Command: "relocate-replicas", Section: "Smart relocation", Description: `Relocates all or part of the replicas of a given instance under another instance`},
	{Command: "take-siblings", Section: "Smart relocation", Description: `Turn all siblings of a replica into its sub-replicas.`},
	{Command: "regroup-replicas", Section: "Smart relocation", Description: `Given an instance, pick one of its replicas and make it local master of its siblings`},
	{Command: "move-up", Section: "Classic file:pos relocation", Description: `Move a replica one level up the topology`},
	{Command: "move-up-replicas", Section: "Classic file:pos relocation", Description: `Moves replicas of the given instance one level up the topology`},
	{Command: "move-below", Section: "Classic file:pos relocation", Description: `Moves a replica beneath its sibling. Both replicas must be actively replicating from same master.`},
	{Command: "move-equivalent", Section: "Classic file:pos relocation", Description: `Moves a replica beneath another server, based on previously recorded "equivalence coordinates"`},
	{Command: "repoint", Section: "Classic file:pos relocation", Description: `Make the given instance replicate from another instance without changing the binglog coordinates. Use with care`},
	{Command: "repoint-replicas", Section: "Classic file:pos relocation", Description: `Repoint all replicas of given instance to replicate back from the instance. Use with care`},
	{Command: "take-master", Section: "Classic file:pos relocation", Description: `Turn an instance into a master of its own master; essentially switch the two.`},
	{Command: "make-co-master", Section: "Classic file:pos relocation", Description: `Create a master-master replication. Given instance is a replica which replicates directly from a master.`},
	{Command: "get-candidate-replica", Section: "Classic file:pos relocation", Description: `Information command suggesting the most up-to-date replica of a given instance that is good for promotion`},
	{Command: "regroup-replicas-bls", Section: "Binlog server relocation", Description: `Regroup Binlog Server replicas of a given instance`},
	{Command: "move-gtid", Section: "GTID relocation", Description: `Move a replica beneath another instance.`},
	{Command: "move-replicas-gtid", Section: "GTID relocation", Description: `Moves all replicas of a given instance under another (destination) instance using GTID`},
	{Command: "regroup-replicas-gtid", Section: "GTID relocation", Description: `Given an instance, pick one of its replica and make it local master of its siblings, using GTID.`},
	{Command: "match", Section: "Pseudo-GTID relocation", Description: `Matches a replica beneath another (destination) instance using Pseudo-GTID`},
	{Command: "match-up", Section: "Pseudo-GTID relocation", Description: `Transport the replica one level up the hierarchy, making it child of its grandparent, using Pseudo-GTID`},
	{Command: "rematch", Section: "Pseudo-GTID relocation", Description: `Reconnect a replica onto its master, via PSeudo-GTID.`},
	{Command: "match-replicas", Section: "Pseudo-GTID relocation", Description: `Matches all replicas of a given instance under another (destination) instance using Pseudo-GTID`},
	{Command: "match-up-replicas", Section: "Pseudo-GTID relocation", Description: `Matches replicas of the given instance one level up the topology, making them siblings of given instance, using Pseudo-GTID`},
	{Command: "regroup-replicas-pgtid", Section: "Pseudo-GTID relocation", Description: `Given an instance, pick one of its replica and make it local master of its siblings, using Pseudo-GTID.`},
	{Command: "enable-gtid", Section: "Replication, general", Description: `If possible, turn on GTID replication`},
	{Command: "disable-gtid", Section: "Replication, general", Description: `Turn off GTID replication, back to file:pos replication`},
	{Command: "which-gtid-errant", Section: "Replication, general", Description: `Get errant GTID set (empty results if no errant GTID)`},
	{Command: "gtid-errant-reset-master", Section: "Replication, general", Description: `Reset master on instance, remove GTID errant transactions`},
	{Command: "skip-query", Section: "Replication, general", Description: `Skip a single statement on a replica; either when running with GTID or without`},
	{Command: "stop-replica", Section: "Replication, general", Description: `Issue a STOP SLAVE on an instance`},
	{Command: "start-replica", Section: "Replication, general", Description: `Issue a START SLAVE on an instance`},
	{Command: "restart-replica", Section: "Replication, general", Description: `STOP and START SLAVE on an instance`},
	{Command: "reset-replica", Section: "Replication, general", Description: `Issues a RESET SLAVE command; use with care`},
	{Command: "change-master-credentials", Section: "Replication, general", Description: `Re-apply replication user/password (and SSL material, if ReplicationCredentialsQuery provides it) on an instance while preserving its existing SOURCE_SSL/TLS configuration.`},
	{Command: "detach-replica-master-host", Section: "Replication, general", Description: `Stops replication and modifies Master_Host into an impossible, yet reversible, value.`},
	{Command: "reattach-replica-master-host", Section: "Replication, general", Description: `Undo a detach-replica-master-host operation`},
	{Command: "master-pos-wait", Section: "Replication, general", Description: `Wait until replica reaches given replication coordinates (--binlog=file:pos)`},
	{Command: "enable-semi-sync-master", Section: "Replication, general", Description: `Enable semi-sync replication (master-side)`},
	{Command: "disable-semi-sync-master", Section: "Replication, general", Description: `Disable semi-sync replication (master-side)`},
	{Command: "enable-semi-sync-replica", Section: "Replication, general", Description: `Enable semi-sync replication (replica-side)`},
	{Command: "disable-semi-sync-replica", Section: "Replication, general", Description: `Disable semi-sync replication (replica-side)`},
	{Command: "restart-replica-statements", Section: "Replication, general", Description: `Get a list of statements to execute to stop then restore replica to same execution state. Provide --statement for injected statement`},
	{Command: "can-replicate-from", Section: "Replication information", Description: `Can an instance (-i) replicate from another (-d) according to replication rules? Prints 'true|false'`},
	{Command: "is-replicating", Section: "Replication information", Description: `Is an instance (-i) actively replicating right now`},
	{Command: "is-replication-stopped", Section: "Replication information", Description: `Is an instance (-i) a replica with both replication threads stopped`},
	{Command: "set-read-only", Section: "Instance", Description: `Turn an instance read-only, via SET GLOBAL read_only := 1`},
	{Command: "set-writeable", Section: "Instance", Description: `Turn an instance writeable, via SET GLOBAL read_only := 0`},
	{Command: "flush-binary-logs", Section: "Binary logs", Description: `Flush binary logs on an instance`},
	{Command: "purge-binary-logs", Section: "Binary logs", Description: `Purge binary logs of an instance`},
	{Command: "last-pseudo-gtid", Section: "Binary logs", Description: `Find latest Pseudo-GTID entry in instance's binary logs`},
	{Command: "locate-gtid-errant", Section: "Binary logs", Description: `List binary logs containing errant GTIDs`},
	{Command: "last-executed-relay-entry", Section: "Binary logs", Description: `Find coordinates of last executed relay log entry`},
	{Command: "correlate-relaylog-pos", Section: "Binary logs", Description: `Given an instance (-i) and relaylog coordinates (--binlog=file:pos), find the correlated coordinates in another instance's relay logs (-d)`},
	{Command: "find-binlog-entry", Section: "Binary logs", Description: `Get binlog file:pos of entry given by --pattern (exact full match, not a regular expression) in a given instance`},
	{Command: "correlate-binlog-pos", Section: "Binary logs", Description: `Given an instance (-i) and binlog coordinates (--binlog=file:pos), find the correlated coordinates in another instance (-d)`},
	{Command: "submit-pool-instances", Section: "Pools", Description: `Submit a pool name with a list of instances in that pool`},
	{Command: "cluster-pool-instances", Section: "Pools", Description: `List all pools and their associated instances`},
	{Command: "which-heuristic-cluster-pool-instances", Section: "Pools", Description: `List instances of a given cluster which are in either any pool or in a specific pool`},
	{Command: "find", Section: "Information", Description: `Find instances whose hostname matches given regex pattern`},
	{Command: "search", Section: "Information", Description: `Search instances by name, version, version comment, port`},
	{Command: "clusters", Section: "Information", Description: `List all clusters known to orchestrator`},
	{Command: "clusters-alias", Section: "Information", Description: `List all clusters known to orchestrator`},
	{Command: "all-clusters-masters", Section: "Information", Description: `List of writeable masters, one per cluster`},
	{Command: "topology", Section: "Information", Description: `Show an ascii-graph of a replication topology, given a member of that topology`},
	{Command: "topology-tabulated", Section: "Information", Description: `Show an ascii-graph of a replication topology, given a member of that topology`},
	{Command: "topology-tags", Section: "Information", Description: `Show an ascii-graph of a replication topology and instance tags, given a member of that topology`},
	{Command: "all-instances", Section: "Information", Description: `The complete list of known instances`},
	{Command: "which-instance", Section: "Information", Description: `Output the fully-qualified hostname:port representation of the given instance, or error if unknown`},
	{Command: "which-cluster", Section: "Information", Description: `Output the name of the cluster an instance belongs to, or error if unknown to orchestrator`},
	{Command: "which-cluster-alias", Section: "Information", Description: `Output the alias of the cluster an instance belongs to, or error if unknown to orchestrator`},
	{Command: "which-cluster-domain", Section: "Information", Description: `Output the domain name of the cluster an instance belongs to, or error if unknown to orchestrator`},
	{Command: "which-heuristic-domain-instance", Section: "Information", Description: `Returns the instance associated as the cluster's writer with a cluster's domain name.`},
	{Command: "which-cluster-master", Section: "Information", Description: `Output the name of the master in a given cluster`},
	{Command: "which-cluster-instances", Section: "Information", Description: `Output the list of instances participating in same cluster as given instance`},
	{Command: "which-cluster-osc-replicas", Section: "Information", Description: `Output a list of replicas in a cluster, that could serve as a pt-online-schema-change operation control replicas`},
	{Command: "which-cluster-gh-ost-replicas", Section: "Information", Description: `Output a list of replicas in a cluster, that could serve as a gh-ost working server`},
	{Command: "which-master", Section: "Information", Description: `Output the fully-qualified hostname:port representation of a given instance's master`},
	{Command: "which-downtimed-instances", Section: "Information", Description: `List instances currently downtimed, potentially filtered by cluster`},
	{Command: "which-replicas", Section: "Information", Description: `Output the fully-qualified hostname:port list of replicas of a given instance`},
	{Command: "which-lost-in-recovery", Section: "Information", Description: `List instances marked as downtimed for being lost in a recovery process`},
	{Command: "instance-status", Section: "Information", Description: `Output short status on a given instance`},
	{Command: "get-cluster-heuristic-lag", Section: "Information", Description: `For a given cluster (indicated by an instance or alias), output a heuristic "representative" lag of that cluster`},
	{Command: "submit-masters-to-kv-stores", Section: "Key-value", Description: `Submit master of a specific cluster, or all masters of all clusters to key-value stores`},
	{Command: "tags", Section: "tags", Description: `List tags for a given instance`},
	{Command: "tag-value", Section: "tags", Description: `Get tag value for a specific instance`},
	{Command: "tagged", Section: "tags", Description: `List instances tagged by tag-string. Format: "tagname" or "tagname=tagvalue" or comma separated "tag0,tag1=val1,tag2" for intersection of all.`},
	{Command: "tag", Section: "tags", Description: `Add a tag to a given instance. Tag in "tagname" or "tagname=tagvalue" format`},
	{Command: "untag", Section: "tags", Description: `Remove a tag from an instance`},
	{Command: "untag-all", Section: "tags", Description: `Remove a tag from all matching instances`},
	{Command: "discover", Section: "Instance management", Description: `Lookup an instance, investigate it`},
	{Command: "forget", Section: "Instance management", Description: `Forget about an instance's existence`},
	{Command: "begin-maintenance", Section: "Instance management", Description: `Request a maintenance lock on an instance`},
	{Command: "end-maintenance", Section: "Instance management", Description: `Remove maintenance lock from an instance`},
	{Command: "in-maintenance", Section: "Instance management", Description: `Check whether instance is under maintenance`},
	{Command: "begin-downtime", Section: "Instance management", Description: `Mark an instance as downtimed`},
	{Command: "end-downtime", Section: "Instance management", Description: `Indicate an instance is no longer downtimed`},
	{Command: "recover", Section: "Recovery", Description: `Do auto-recovery given a dead instance`},
	{Command: "recover-lite", Section: "Recovery", Description: `Do auto-recovery given a dead instance. Orchestrator chooses the best course of actionwithout executing external processes`},
	{Command: "force-master-failover", Section: "Recovery", Description: `Forcibly discard master and initiate a failover, even if orchestrator doesn't see a problem. This command lets orchestrator choose the replacement master`},
	{Command: "force-master-takeover", Section: "Recovery", Description: `Forcibly discard master and promote another (direct child) instance instead, even if everything is running well`},
	{Command: "graceful-master-takeover", Section: "Recovery", Description: `Gracefully promote a new master. Either indicate identity of new master via '-d designated.instance.com' or setup replication tree to have a single direct replica to the master.`},
	{Command: "graceful-master-takeover-auto", Section: "Recovery", Description: `Gracefully promote a new master. orchestrator will attempt to pick the promoted replica automatically`},
	{Command: "replication-analysis", Section: "Recovery", Description: `Request an analysis of potential crash incidents in all known topologies`},
	{Command: "ack-all-recoveries", Section: "Recovery", Description: `Acknowledge all recoveries; this unblocks pending future recoveries`},
	{Command: "ack-cluster-recoveries", Section: "Recovery", Description: `Acknowledge recoveries for a given cluster; this unblocks pending future recoveries`},
	{Command: "ack-instance-recoveries", Section: "Recovery", Description: `Acknowledge recoveries for a given instance; this unblocks pending future recoveries`},
	{Command: "register-candidate", Section: "Instance, meta", Description: `Indicate that a specific instance is a preferred candidate for master promotion`},
	{Command: "register-hostname-unresolve", Section: "Instance, meta", Description: `Assigns the given instance a virtual (aka "unresolved") name`},
	{Command: "deregister-hostname-unresolve", Section: "Instance, meta", Description: `Explicitly deregister/dosassociate a hostname with an "unresolved" name`},
	{Command: "set-heuristic-domain-instance", Section: "Instance, meta", Description: `Associate domain name of given cluster with what seems to be the writer master for that cluster`},
	{Command: "snapshot-topologies", Section: "Meta", Description: `Take a snapshot of existing topologies.`},
	{Command: "continuous", Section: "Meta", Description: `Enter continuous mode, and actively poll for instances, diagnose problems, do maintenance`},
	{Command: "active-nodes", Section: "Meta", Description: `List currently active orchestrator nodes`},
	{Command: "access-token", Section: "Meta", Description: `Get a HTTP access token`},
	{Command: "resolve", Section: "Meta", Description: `Resolve given hostname`},
	{Command: "reset-hostname-resolve-cache", Section: "Meta", Description: `Clear the hostname resolve cache`},
	{Command: "dump-config", Section: "Meta", Description: `Print out configuration in JSON format`},
	{Command: "show-resolve-hosts", Section: "Meta", Description: `Show the content of the hostname_resolve table. Generally used for debugging`},
	{Command: "show-unresolve-hosts", Section: "Meta", Description: `Show the content of the hostname_unresolve table. Generally used for debugging`},
	{Command: "redeploy-internal-db", Section: "Meta, internal", Description: `Force internal schema migration to current backend structure`},
	{Command: "internal-suggest-promoted-replacement", Section: "Internal", Description: `Internal only, used to test promotion logic in CI`},
	{Command: "custom-command", Section: "Agent", Description: "Execute a custom command on the agent as defined in the agent conf"},
	{Command: "disable-global-recoveries", Section: "", Description: `Disallow orchestrator from performing recoveries globally`},
	{Command: "enable-global-recoveries", Section: "", Description: `Allow orchestrator to perform recoveries globally`},
	{Command: "check-global-recoveries", Section: "", Description: `Show the global recovery configuration`},
	{Command: "bulk-instances", Section: "", Description: `Return a list of sorted instance names known to orchestrator`},
	{Command: "bulk-promotion-rules", Section: "", Description: `Return a list of promotion rules known to orchestrator`},
}

// commandDefinitions 返回独立的命令目录，包含兼容旧名称的别名。
func commandDefinitions() []commandDefinition {
	commands := slices.Clone(knownCommands)
	for i := range commands {
		for alias, canonical := range commandSynonyms {
			if canonical == commands[i].Command {
				commands[i].Aliases = append(commands[i].Aliases, alias)
			}
		}
		slices.Sort(commands[i].Aliases)
	}
	return commands
}
