name: CI

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '13 */4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Test modules
      run: make deps

    - name: Test source code
      run: make fmt-check

    - name: Test build
      run: make build

    - name: Test unit
      run: make test-unit

    - name: Update packages
      run:  sudo apt-get update

    - name: Set up SQLite
      run:  sudo apt-get install sqlite3

    - name: Start local MySQL
      run:  sudo /etc/init.d/mysql start

    - name: Test integration
      run: make test-integration

    - name: Test documentation
      run: make test-docs

    - name: Upload orchestrator binary artifact
      uses: actions/upload-artifact@v7
      with:
        name: orchestrator
        path: bin/orchestrator
