name: system tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '43 */4 * * *'

jobs:
  system:
    runs-on: ubuntu-latest

    steps:
    - name: check out
      uses: actions/checkout@v6

    - name: Run containerized system tests
      env:
        RUN_TESTS: "YES"
      run: script/dock system-no-it
